Update test.yml

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -45,13 +45,20 @@ jobs:
     needs: build
     runs-on: ubuntu-latest
     steps:
-    - name: Install pytest
+    - name: Set up Python
+      uses: actions/setup-python@v2
+      with:
+        python-version: '3.10'
+    - name: Checkout repository
+      uses: actions/checkout@v2
+    - name: Install dependencies
       run: |
-        python -m pip install pytest
-
-    - name: Run unit test with pytest
+        python -m pip install --upgrade pip
+        pip install -r requirements.txt
+        if [ ! -f requirements.txt ]; then echo "Error: requirements.txt not found"; exit 1; fi
+    - name: Run unit tests
       run: |
-        python -m pytest test_unit-test.py
+        pytest --ignore=env
     
           
   static-code-analysis:
